FROM node:latest AS dependencies

WORKDIR /home/app

COPY package*.json /home/app
RUN npm install -g cnpm --registry=https://registry.npmmirror.com
RUN cnpm install

COPY . /home/app

CMD [ "node","/home/app/hot-import-bot.js" ]